name: lenskit
channels:
- c
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_1
- ipython_genutils=0.1.0=py35_0
- jbig=2.1=0
- jinja2=2.8=py35_1
- jpeg=8d=2
- jsonschema=2.5.1=py35_0
- jupyter_client=4.2.2=py35_0
- jupyter_core=4.1.0=py35_0
- libgcc=4.8.5=1
- libpng=1.6.22=0
- libtiff=4.0.6=1
- libxml2=2.9.2=1
- markupsafe=0.23=py35_2
- mistune=0.7.2=py35_1
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- ncurses=5.9=1
- notebook=4.2.1=py35_0
- openssl=1.0.2h=1
- path.py=8.2.1=py35_0
- pcre=8.31=0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- python=3.5.1=0
- python.app=1.2=py35_4
- pyzmq=15.2.0=py35_1
- r=3.2.2=0
- r-assertthat=0.1=r3.2.2_2a
- r-base=3.2.2=0
- r-base64enc=0.1_3=r3.2.2_0a
- r-bh=1.58.0_1=r3.2.2_0a
- r-boot=1.3_17=r3.2.2_0a
- r-class=7.3_14=r3.2.2_0a
- r-cluster=2.0.3=r3.2.2_0a
- r-codetools=0.2_14=r3.2.2_0a
- r-colorspace=1.2_6=r3.2.2_0a
- r-dbi=0.3.1=r3.2.2_3a
- r-dichromat=2.0_0=r3.2.2_3a
- r-digest=0.6.8=r3.2.2_3a
- r-dplyr=0.4.3=r3.2.2_0a
- r-evaluate=0.8=r3.2.2_0a
- r-foreign=0.8_66=r3.2.2_0a
- r-ggplot2=1.0.1=r3.2.2_0a
- r-gtable=0.1.2=r3.2.2_3a
- r-irdisplay=0.3=r3.2.2_0a
- r-irkernel=0.5=r3.2.2_2
- r-jsonlite=0.9.17=r3.2.2_0a
- r-kernsmooth=2.23_15=r3.2.2_0a
- r-labeling=0.3=r3.2.2_2a
- r-lattice=0.20_33=r3.2.2_0a
- r-lazyeval=0.1.10=r3.2.2_3a
- r-magrittr=1.5=r3.2.2_2a
- r-mass=7.3_45=r3.2.2_0a
- r-matrix=1.2_2=r3.2.2_0a
- r-mgcv=1.8_9=r3.2.2_0a
- r-munsell=0.4.2=r3.2.2_2a
- r-nlme=3.1_122=r3.2.2_0a
- r-nnet=7.3_11=r3.2.2_0a
- r-plyr=1.8.3=r3.2.2_0a
- r-proto=0.3_10=r3.2.2_2a
- r-r6=2.1.1=r3.2.2_0a
- r-rcolorbrewer=1.1_2=r3.2.2_3a
- r-rcpp=0.12.2=r3.2.2_0a
- r-recommended=3.2.2=r3.2.2_0
- r-repr=0.3=r3.2.2_0a
- r-reshape2=1.4.1=r3.2.2_2a
- r-rpart=4.1_10=r3.2.2_0a
- r-rzmq=0.7.7=r3.2.2_2a
- r-scales=0.3.0=r3.2.2_0a
- r-spatial=7.3_11=r3.2.2_0a
- r-stringi=1.0_1=r3.2.2_0a
- r-stringr=1.0.0=r3.2.2_0a
- r-survival=2.38_3=r3.2.2_0a
- r-uuid=0.1_2=r3.2.2_0a
- readline=6.2=2
- setuptools=22.0.5=py35_0
- simplegeneric=0.8.1=py35_1
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zeromq=4.1.3=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - nbstripout==0.2.6

